dependencies:
- name: dmc-ui
  version: '0.1'
  repository: 'file://../dmc-ui'
  alias: ui
- name: dmc-apim
  version: '0.1'
  repository: 'file://../dmc-apim'
  alias: apim-api
- name: dmc-user
  version: '0.1'
  repository: 'file://../dmc-user'
  alias: user-api
- name: dmc-proxy
  version: '0.1'
  repository: 'file://../dmc-proxy'
  alias: proxy
- name: dmc-api-runner
  version: '0.1'
  repository: 'file://../dmc-api-runner'
  alias: api-runner
- name: mysql
  version: '0.6.0'
  repository: 'file://../../common/mysql'
  alias: mysql
- name: presto
  version: '0.2'
  repository: 'file://../../common/presto'
  alias: presto