logging:
  level:
    ROOT: INFO
    com.zhuxun: TRACE
spring:
  profiles:
    active: dev
    include: swagger
  jackson:
    serialization.indent_output: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db:3306/dmc_api?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: testing

server:
  port: 80
  servlet:
    context-path: /

application:
  security:
    authentication:
      jwt:
        secret: secret
        tokenValidityInSeconds: 36000
        tokenValidityInSecondsForRememberMe: 360000
