apiVersion: v1
kind: Secret
metadata:
  name: {{ template "springapp.fullname" . }}
  labels:
    app: {{ template "springapp.name" . }}
    chart: {{ template "springapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  application.yaml: {{ .Values.application_sec | toYaml | b64enc }}
