# Default values for dmc.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dmc-api-runner
  tag: 0.1
  pullPolicy: IfNotPresent

container:
  appJar: /app.jar
  config:
    path: /app/config
  probePath: v2/api-docs

service:
  type: ClusterIP
  port: 9003

config:
  logging:
    level:
      ROOT: INFO
      com.zhuxun: TRACE

  spring:
    jackson:
      serialization.indent_output: true
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://dmc-db-mysql:3306/dmc_api?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
      username: root
      password:

  server:
    port: 80
    servlet:
      context-path: /

  application:
    managedDatasource:
      dsConfigDir: /app/ds-config
    security:
      authentication:
        jwt:
          secret: secret
          tokenValidityInSeconds: 3600
          tokenValidityInSecondsForRememberMe: 360000

# =============================================================================
# 受管数据源配置
# =============================================================================
catalog:
  dmc_api.properties: |
    connector.name=mysql
    connection-url=jdbc:mysql://dmc-db-mysql:3306/dmc_api
    connection-user=root
    connection-password=testing

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
