apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dmc-api-runner.fullname" . }}
  labels:
    app: {{ template "dmc-api-runner.name" . }}
    chart: {{ template "dmc-api-runner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: apim-api
data:
  application.yaml: |-
{{ include "dmc-api-runner.config" . | indent 4 }}
  launch.sh: |
    java -jar -Dfile.encoding=UTF8 -Duser.timezone=GMT+08 {{ .Values.container.appJar }} --spring.config.location={{ printf "%s/application.yaml" .Values.container.config.path }}
