apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dmc-apim.fullname" . }}
  labels:
    app: {{ template "dmc-apim.name" . }}
    chart: {{ template "dmc-apim.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{ include "dmc-apim.catalog" . | indent 2 }}
