apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "springapp.fullname" . }}
  labels:
    app: {{ template "springapp.name" . }}
    chart: {{ template "springapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  application.yaml: {{ printf "|\n%s" (.Values.application | toYaml | indent 4) }}
  launch.sh: |
    cat {{ template "springapp.config.rgl" . }}/application.yaml {{ template "springapp.config.sec" . }}/application.yaml > {{ printf "%s/application.yaml" .Values.container.config.path }}
    java -jar -Dfile.encoding=UTF8 -Duser.timezone=GMT+08 {{ .Values.container.appJar }} --spring.config.location={{ printf "%s/application.yaml" .Values.container.config.path }}
