version: "2"
services:

  coordinator-1:
    container_name: coordinator-1
    networks: ["vnet"]
    hostname: coordinator-1.vnet
    image: presto:0.208
    ports:
      - 8080:8080
    command: coordinator
    environment:
      - PRESTO_DISCOVERY_URI=http://coordinator-1.vnet:8080

  worker-1:
    container_name: worker-1
    networks: ["vnet"]
    hostname: worker-1.vnet
    image: presto:0.208
    depends_on: ["coordinator-1"]
    command: worker
    environment:
      - PRESTO_DISCOVERY_URI=http://coordinator-1.vnet:8080

  worker-2:
    container_name: worker-2
    networks: ["vnet"]
    hostname: worker-2.vnet
    image: presto:0.208
    depends_on: ["coordinator-1"]
    command: worker
    environment:
      - PRESTO_DISCOVERY_URI=http://coordinator-1.vnet:8080

networks:
  vnet:
    external:
      name: vnet
