apiVersion: v1
kind: Secret
metadata:
  name: {{ template "presto.catalog" . }}
  labels:
    app: {{ template "presto.name" . }}
    chart: {{ template "presto.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: catalog
type: Opaque
data:
{{ include "presto.catalog-values" . | indent 2 }}